import * as yup from 'yup';

export const createJobSchema = yup.object().shape({
    title: yup.string().required('Title is required'),
    description: yup.string().required('Description is required'),
    deadline: yup.date().required(),
    link: yup.string().optional(),
    source: yup.string().optional(),
    level: yup.string().required('Experience level is required'),
    duration: yup.string().required('Duration is required'),
    job_post_status: yup.string().optional(),
    city: yup.string().required('Title is required'),
    country: yup.string().required('Title is required'),
    state: yup.string().required('Title is required'),
    workLocation: yup.string().required('WorkLocation is required'),
    skill_requirements: yup.string().required('Please enter skill requirements'),
    niceToHave: yup.string().optional(),
    experience: yup.string().optional(),
    responsibilities: yup.string().required('Title is required'),
    benefits: yup.string().required('Title is required'),
    from: yup.string().optional(),
    to: yup.string().optional(),
    currency: yup.string().optional(),
    tags: yup.string().required(' tags are required'),
    employerID: yup.string().optional(),
})


// title,
// description,
// deadline,
// link,
// source,
// level,
// duration,
// job_post_status,
// city,
// country,
// state,
// workLocation,
// skill_requirements,
// niceToHave,
// experience,
// responsibilities,
// benefits,
// from,
// to,
// tags,
// employerID
